### ISSUE TITLE
[homeassistant.setup] Setup failed for webehome: Integration not found.

### ISSUE THREAD

**Issue by ekkelenkamp** [bratanon/ha-webehome#4]
Hallo,

I'm tring to setup the webehome integration with my home assistant. I added the webehome config to my configuration.yaml like this. But  this results in the error: Setup failed for webehome: Integration not found.

Is this the correct way to configure webehome?

```
default_config:
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  auth_providers:
    - type: legacy_api_password
      api_password: !secret http_password

webehome:
  username: !secret webehome_username
  password: !secret webehome_password
```
