### ISSUE TITLE
Motion detectors (PIR) do report ON al the time

### ISSUE THREAD

**Issue by ekkelenkamp** [bratanon/ha-webehome#5]
I'm trying to use the webhome entities in my Home Assistant 2022.11.1 version.
I'm  trying to use the magnetic contacts and motion detectors.

The Magnetic contacts are working fine.
The Motion detectors (PIR) do report ON al the time, so I cannot use them to trigger anything. Is this a known issue? In the webhome app the motion detection is working fine and reports correct times a motion was detect.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/7031474/201433673-5ded0cda-6779-473e-a4e3-d8658a95c165.png">

**Comment by ekkelenkamp** [comment]
After some debugging, it looks like a state attribute should be used for this. You can check if the value of the last_event_time attribute has been changed. 
In my automation I did something like this: 
```
 trigger:
  - platform: state
    entity_id:
    - binary_sensor.pir_trigger_my_motion_detector
    attribute: last_event_time
  action:
```

Is this the correct way to handle motion detection events?
It is still unclear to my why the ON is reporting (does this only mean that the PIR is working correctly?)
